"""Tests for configurable evaluation budgets and cancellation.

The tests use deterministic, generated inputs and assert exact work-unit
counts; they never rely on wall clock time or the file system.
"""
import threading
import unittest

import jmespath
from jmespath import exceptions
from jmespath import functions
from jmespath.budget import (
    BudgetCategory as B,
    CancellationToken,
)


def run_with_snapshot(expression, data, options=None):
    holder = {}
    options = _with_observer(options, holder)
    result = jmespath.search(expression, data, options)
    return result, holder['snapshot']


def _with_observer(options, holder):
    def observe(snapshot):
        holder['snapshot'] = snapshot
    if options is None:
        return jmespath.Options(budget_observer=observe)
    # Preserve any existing configuration while adding the observer.
    return jmespath.Options(
        dict_cls=options.dict_cls,
        custom_functions=options.custom_functions,
        budget_limits=options.budget_limits,
        total_budget=options.total_budget,
        cancellation_token=options.cancellation_token,
        budget_observer=observe)


class ExactCountTests(unittest.TestCase):
    def test_projection_null_filtering_counts(self):
        # Three array elements are visited; only the two non-null RHS
        # values populate the intermediate list.
        data = {'foo': [{'bar': 1}, {}, {'bar': 2}]}
        result, snapshot = run_with_snapshot('foo[*].bar', data)
        self.assertEqual(result, [1, 2])
        self.assertEqual(snapshot.consumed[B.ARRAY_ITERATION], 3)
        self.assertEqual(snapshot.consumed[B.GENERATED_ELEMENT], 2)

    def test_filter_projection_charges_per_element_and_match(self):
        data = {'foo': [
            {'bar': 3, 'name': 'a'},
            {'bar': 1, 'name': 'b'},
            {'bar': 4, 'name': 'c'},
        ]}
        result, snapshot = run_with_snapshot(
            'foo[?bar > `2`].name', data)
        self.assertEqual(result, ['a', 'c'])
        self.assertEqual(snapshot.consumed[B.ARRAY_ITERATION], 3)
        self.assertEqual(snapshot.consumed[B.COMPARISON], 3)
        self.assertEqual(snapshot.consumed[B.GENERATED_ELEMENT], 2)

    def test_flatten_charges_inputs_and_outputs(self):
        data = {'foo': [[1, 2], [3], 4]}
        result, snapshot = run_with_snapshot('foo[]', data)
        self.assertEqual(result, [1, 2, 3, 4])
        # The flatten node examines three outer elements and three
        # elements pulled out of the nested lists (the scalar is only
        # generated), then the implicit projection re-walks the four
        # flattened outputs to filter nulls.
        flatten_iterations = 6
        projection_iterations = 4
        self.assertEqual(
            snapshot.consumed[B.ARRAY_ITERATION],
            flatten_iterations + projection_iterations)
        # Four elements are generated by flatten and four survive the
        # implicit projection.
        self.assertEqual(snapshot.consumed[B.GENERATED_ELEMENT], 8)

    def test_or_short_circuit_skips_right_subtree(self):
        data = {'a': 1, 'b': 2}
        _, taken = run_with_snapshot('a || b', data)
        _, short_circuited = run_with_snapshot('a || b', {'a': None,
                                                          'b': 2})
        self.assertEqual(
            taken.consumed[B.AST_VISIT] + 1,
            short_circuited.consumed[B.AST_VISIT])
        # Neither branch is compared/iterated.
        self.assertEqual(taken.consumed[B.COMPARISON], 0)
        self.assertEqual(short_circuited.consumed[B.COMPARISON], 0)

    def test_pipe_materializes_left_side(self):
        data = {'a': [1, 2, 3]}
        result, snapshot = run_with_snapshot('a | length(@)', data)
        self.assertEqual(result, 3)
        # The pipe node itself adds no work beyond visiting both operands.
        self.assertEqual(snapshot.consumed[B.FUNCTION_CALL], 1)
        self.assertEqual(snapshot.consumed[B.ARRAY_ITERATION], 0)

    def test_equality_comparisons_counted_once(self):
        _, snapshot = run_with_snapshot('a == b', {'a': 1, 'b': 1})
        self.assertEqual(snapshot.consumed[B.COMPARISON], 1)

    def test_ordering_type_mismatch_is_not_a_comparison(self):
        # Booleans are not comparable in JMESPath: neither operand is
        # comparable here, so no comparison is performed.
        result, snapshot = run_with_snapshot(
            'a < b', {'a': True, 'b': 'x'})
        self.assertIsNone(result)
        self.assertEqual(snapshot.consumed[B.COMPARISON], 0)

    def test_sort_by_is_stable_and_counted(self):
        people = [
            {'age': 1, 'name': 'a'},
            {'age': 1, 'name': 'b'},
            {'age': 1, 'name': 'c'},
        ]
        result, snapshot = run_with_snapshot(
            'sort_by(people, &age)[].name', {'people': people})
        self.assertEqual(result, ['a', 'b', 'c'])
        # sort_by spends one probe evaluation plus n key evaluations
        # (4 array iterations), the array-typed argument is scanned once
        # by signature validation (3), and the trailing projection walks
        # the three results (3).
        self.assertEqual(snapshot.consumed[B.ARRAY_ITERATION], 10)
        # Sorting three keys with two equal keys performs two comparisons.
        self.assertEqual(snapshot.consumed[B.COMPARISON], 2)

    def test_max_by_empty_array_is_free_besides_call(self):
        result, snapshot = run_with_snapshot(
            'max_by(empty, &x)', {'empty': []})
        self.assertIsNone(result)
        self.assertEqual(snapshot.consumed[B.FUNCTION_CALL], 1)
        self.assertEqual(snapshot.consumed[B.ARRAY_ITERATION], 0)
        self.assertEqual(snapshot.consumed[B.COMPARISON], 0)

    def test_max_by_nonempty_counts(self):
        result, snapshot = run_with_snapshot(
            'max_by(items, &x)', {'items': [{'x': 1}, {'x': 2}]})
        self.assertEqual(result, {'x': 2})
        self.assertEqual(snapshot.consumed[B.ARRAY_ITERATION], 2)
        self.assertEqual(snapshot.consumed[B.COMPARISON], 1)


class EndpointSemanticsTests(unittest.TestCase):
    DATA = {'foo': [{'bar': 1}, {'bar': 2}, {'bar': 3}]}
    EXPRESSION = 'foo[*].bar'

    def test_consuming_exactly_the_limit_succeeds(self):
        # The expression consumes exactly five AST visits.
        options = jmespath.Options(
            budget_limits={B.AST_VISIT: 5})
        self.assertEqual(
            jmespath.search(self.EXPRESSION, self.DATA, options),
            [1, 2, 3])

    def test_one_unit_past_the_limit_fails(self):
        options = jmespath.Options(
            budget_limits={B.AST_VISIT: 4})
        with self.assertRaises(exceptions.BudgetExceededError) as caught:
            jmespath.search(self.EXPRESSION, self.DATA, options)
        error = caught.exception
        self.assertEqual(error.category, B.AST_VISIT)
        self.assertEqual(error.attempted, 5)
        self.assertEqual(error.category_limit, 4)
        self.assertGreaterEqual(error.attempted_total, 5)

    def test_zero_limit_fails_on_first_unit(self):
        options = jmespath.Options(
            budget_limits={B.AST_VISIT: 0})
        with self.assertRaises(exceptions.BudgetExceededError):
            jmespath.search('a', {'a': 1}, options)

    def test_total_limit_aggregates_categories(self):
        _, snapshot = run_with_snapshot(self.EXPRESSION, self.DATA)
        options = jmespath.Options(total_budget=snapshot.total_consumed)
        self.assertEqual(
            jmespath.search(self.EXPRESSION, self.DATA, options), [1, 2, 3])
        options = jmespath.Options(
            total_budget=snapshot.total_consumed - 1)
        with self.assertRaises(exceptions.BudgetExceededError) as caught:
            jmespath.search(self.EXPRESSION, self.DATA, options)
        self.assertIsNone(caught.exception.category_limit)
        self.assertEqual(caught.exception.total_limit,
                         snapshot.total_consumed - 1)

    def test_default_options_remain_unlimited(self):
        self.assertEqual(
            jmespath.search(self.EXPRESSION, self.DATA), [1, 2, 3])

    def test_invalid_limits_fail_construction(self):
        with self.assertRaises(ValueError):
            jmespath.Options(budget_limits={B.AST_VISIT: -1})
        with self.assertRaises(ValueError):
            jmespath.Options(budget_limits={'unknown': 1})
        with self.assertRaises(ValueError):
            jmespath.Options(total_budget='lots')


class ErrorDiagnosticsTests(unittest.TestCase):
    def test_error_carries_locations_and_counters(self):
        options = jmespath.Options(
            budget_limits={B.ARRAY_ITERATION: 1})
        with self.assertRaises(exceptions.BudgetExceededError) as caught:
            jmespath.search('a.b[*].c',
                            {'a': {'b': [{'c': 1}, {'c': 2}]}},
                            options)
        error = caught.exception
        self.assertEqual(error.expression, 'a.b[*].c')
        self.assertIn('projection', error.ast_path)
        self.assertTrue(error.data_path.startswith('$'))
        for category in (B.AST_VISIT, B.ARRAY_ITERATION, B.COMPARISON,
                         B.FUNCTION_CALL, B.GENERATED_ELEMENT):
            self.assertIn(category, error.consumed)
        message = str(error)
        self.assertIn('a.b[*].c', message)
        self.assertIn('ast path', message)
        self.assertIn('data path', message)

    def test_error_never_serializes_user_data(self):
        secret = {'secret-marker': 'do-not-leak'}
        options = jmespath.Options(budget_limits={B.AST_VISIT: 1})
        with self.assertRaises(exceptions.BudgetExceededError) as caught:
            jmespath.search('items[*].v',
                            {'items': [secret]}, options)
        self.assertNotIn('do-not-leak', str(caught.exception))
        self.assertNotIn('secret-marker', str(caught.exception))


class CancellationTests(unittest.TestCase):
    def test_cancelled_token_aborts_with_dedicated_exception(self):
        token = CancellationToken()
        token.cancel()
        options = jmespath.Options(cancellation_token=token)
        with self.assertRaises(exceptions.JMESPathCancelledError) as caught:
            jmespath.search('items[*].v',
                            {'items': [{'v': 1}, {'v': 2}]}, options)
        error = caught.exception
        self.assertIn('projection', error.ast_path)
        self.assertTrue(error.data_path.startswith('$'))

    def test_cancellation_is_distinct_from_budget_and_type_errors(self):
        self.assertFalse(
            issubclass(exceptions.JMESPathCancelledError,
                       exceptions.BudgetExceededError))
        self.assertNotEqual(
            exceptions.JMESPathCancelledError, exceptions.JMESPathTypeError)
        self.assertNotEqual(
            exceptions.JMESPathCancelledError, exceptions.ArityError)

    def test_uncancelled_token_runs_normally(self):
        token = CancellationToken()
        options = jmespath.Options(cancellation_token=token)
        self.assertEqual(
            jmespath.search('a', {'a': 1}, options), 1)


class CustomFunctionTests(unittest.TestCase):
    def _custom_options(self, **kwargs):
        return jmespath.Options(custom_functions=self._functions(), **kwargs)

    def setUp(self):
        class CustomFunctions(functions.Functions):
            @functions.signature({'types': ['array']})
            def _func_heavy(self, arg):
                ctx = jmespath.function_context()
                for _ in arg:
                    ctx.charge(B.ARRAY_ITERATION, 10)
                return len(arg)

            @functions.signature({'types': []})
            def _func_nested(self, arg):
                return jmespath.search('inner[*].x',
                                       {'inner': [{'x': 1}, {'x': 2}]})

            @functions.signature({'types': []})
            def _func_nested_limited(self, arg):
                child = jmespath.Options(
                    budget_limits={B.AST_VISIT: 10 ** 6})
                return jmespath.search('inner[*].x',
                                       {'inner': [{'x': 1}, {'x': 2}]},
                                       child)

        self._functions = CustomFunctions

    def test_custom_function_can_spend_budget(self):
        options = self._custom_options(
            budget_limits={B.ARRAY_ITERATION: 30})
        self.assertEqual(
            jmespath.search('heavy(items)', {'items': [1, 2, 3]}, options),
            3)
        options = self._custom_options(
            budget_limits={B.ARRAY_ITERATION: 25})
        with self.assertRaises(exceptions.BudgetExceededError):
            jmespath.search('heavy(items)', {'items': [1, 2, 3]}, options)

    def test_context_is_absent_outside_search(self):
        self.assertIsNone(jmespath.function_context())

    def test_nested_search_inherits_parent_budget(self):
        holder = {}
        options = self._custom_options(
            budget_observer=lambda s: holder.setdefault('s', s))
        self.assertEqual(
            jmespath.search('nested(`null`)', None, options), [1, 2])
        self.assertGreater(holder['s'].total_consumed, 0)

    def test_nested_search_cannot_reset_parent_budget(self):
        options = self._custom_options(
            budget_limits={B.AST_VISIT: 2})
        with self.assertRaises(exceptions.BudgetExceededError):
            jmespath.search('nested_limited(`null`)', None, options)

    def test_arity_and_type_errors_are_not_budget_errors(self):
        # length() requires exactly one argument.
        with self.assertRaises(exceptions.ArityError):
            jmespath.search('length()', {})
        options = self._custom_options(
            budget_limits={B.AST_VISIT: 10 ** 6})
        # heavy() requires an array.
        with self.assertRaises(exceptions.JMESPathTypeError):
            jmespath.search('heavy(`"x"`)', None, options)

    def test_function_call_is_charged_before_validation(self):
        # The call unit is consumed even though the argument type is wrong.
        holder = {}
        options = self._custom_options(
            budget_limits={B.FUNCTION_CALL: 0},
            budget_observer=lambda s: holder.setdefault('s', s))
        with self.assertRaises(exceptions.BudgetExceededError):
            jmespath.search('length(`"abc"`)', None, options)


class ConcurrencyAndCacheTests(unittest.TestCase):
    EXPRESSION = 'items[*].value'

    def setUp(self):
        self.data = {'items': [{'value': i} for i in range(40)]}
        self.compiled = jmespath.compile(self.EXPRESSION)

    def test_ast_shared_across_searches(self):
        second = jmespath.compile(self.EXPRESSION)
        self.assertIs(self.compiled.parsed, second.parsed)

    def test_different_budgets_run_concurrently(self):
        failures = []

        def run(limit, should_fail):
            options = jmespath.Options(
                budget_limits={B.ARRAY_ITERATION: limit})
            try:
                result = self.compiled.search(self.data, options)
                if should_fail:
                    failures.append('expected failure for limit %d' % limit)
                elif len(result) != 40:
                    failures.append('wrong result length')
            except exceptions.BudgetExceededError:
                if not should_fail:
                    failures.append('unexpected failure for limit %d' % limit)

        threads = []
        for _ in range(6):
            threads.append(threading.Thread(
                target=run, args=(10, True)))
            threads.append(threading.Thread(
                target=run, args=(10 ** 6, False)))
        for thread in threads:
            thread.start()
        for thread in threads:
            thread.join()
        self.assertEqual(failures, [])


class ObserverTests(unittest.TestCase):
    def test_observer_receives_snapshot_on_success_and_failure(self):
        calls = []
        options = jmespath.Options(
            budget_limits={B.AST_VISIT: 1},
            budget_observer=calls.append)
        with self.assertRaises(exceptions.BudgetExceededError):
            jmespath.search('a.b', {'a': {'b': 1}}, options)
        self.assertEqual(len(calls), 1)
        # The rejected charge is not recorded; one visit succeeded.
        self.assertEqual(calls[0].consumed[B.AST_VISIT], 1)

        calls = []
        options = jmespath.Options(budget_observer=calls.append)
        jmespath.search('a', {'a': 1}, options)
        self.assertEqual(len(calls), 1)
        self.assertEqual(calls[0].consumed[B.AST_VISIT], 1)

    def test_budget_error_is_a_jmespath_error(self):
        self.assertTrue(issubclass(
            exceptions.BudgetExceededError, exceptions.JMESPathError))
        self.assertTrue(issubclass(
            exceptions.JMESPathCancelledError, exceptions.JMESPathError))
        self.assertFalse(issubclass(
            exceptions.BudgetExceededError, exceptions.ParseError))


class DeterministicResourceBoundaryTests(unittest.TestCase):
    """Generated deep/wide expressions prove bounds without timeouts."""

    def test_wide_projection_is_bounded_by_array_iteration_budget(self):
        width = 1000
        data = {'items': [{'value': i} for i in range(width)]}
        options = jmespath.Options(
            budget_limits={B.ARRAY_ITERATION: width - 1})
        with self.assertRaises(exceptions.BudgetExceededError) as caught:
            jmespath.search('items[*].value', data, options)
        self.assertEqual(
            caught.exception.category, B.ARRAY_ITERATION)
        # Exactly width iterations are needed; width - 1 must fail.
        options = jmespath.Options(
            budget_limits={B.ARRAY_ITERATION: width})
        self.assertEqual(
            jmespath.search('items[*].value', data, options),
            list(range(width)))

    def test_deeply_nested_expression_is_bounded_by_visit_budget(self):
        depth = 200
        expression = 'a' + '.b' * depth
        chain = {}
        current = chain
        for _ in range(depth - 1):
            current['b'] = {}
            current = current['b']
        current['b'] = 'leaf'
        data = {'a': chain}
        # The AST visits one subexpression node plus depth+1 field nodes.
        needed = depth + 2
        options = jmespath.Options(
            budget_limits={B.AST_VISIT: needed - 1})
        with self.assertRaises(exceptions.BudgetExceededError):
            jmespath.search(expression, data, options)
        options = jmespath.Options(
            budget_limits={B.AST_VISIT: needed})
        self.assertEqual(
            jmespath.search(expression, data, options), 'leaf')

    def test_deep_flatten_chain_is_bounded(self):
        # Generate nested arrays: each flatten level doubles traversal
        # opportunities but the data itself stays small in surface size.
        depth = 100
        value = [0]
        for _ in range(depth):
            value = [value]
        expression = 'x' + '[]' * depth
        data = {'x': value}
        options = jmespath.Options(
            budget_limits={B.GENERATED_ELEMENT: depth})
        with self.assertRaises(exceptions.BudgetExceededError):
            jmespath.search(expression, data, options)

    def test_large_sort_is_bounded_by_comparison_budget(self):
        size = 50
        data = {'items': [{'k': (i * 7) % size} for i in range(size)]}
        # Sorting n distinct keys performs at least n - 1 comparisons.
        options = jmespath.Options(
            budget_limits={B.COMPARISON: size - 2})
        with self.assertRaises(exceptions.BudgetExceededError) as caught:
            jmespath.search('sort_by(items, &k)', data, options)
        self.assertEqual(caught.exception.category, B.COMPARISON)

    def test_function_heavy_expression_bounded_by_call_budget(self):
        depth = 50
        expression = 'abs(' * depth + '`1`' + ')' * depth
        options = jmespath.Options(
            budget_limits={B.FUNCTION_CALL: depth - 1})
        with self.assertRaises(exceptions.BudgetExceededError) as caught:
            jmespath.search(expression, {}, options)
        self.assertEqual(caught.exception.category, B.FUNCTION_CALL)
        options = jmespath.Options(
            budget_limits={B.FUNCTION_CALL: depth})
        self.assertEqual(jmespath.search(expression, {}, options), 1)
